### ISSUE TITLE
could not connect to server

### ISSUE THREAD

**Issue by rvpn** [zzzkeil/Wireguard-DNScrypt-VPN-Server#1]
connection could not be established.

any idea what's wrong with my configuration? this is fresh / clean install on digital ocean both ubuntu 18 & debian 8 both result in this ,

![xjalan](https://user-images.githubusercontent.com/28747439/54471323-09961800-47f2-11e9-89b4-b426c73aca57.PNG)

**Comment by zzzkeil** [comment]
Hi, 
can you try this with the official Wireguard Windows App ?
https://www.wireguard.com/install/#windows-pre-alpha

I don´t use TunSave ....
