### ISSUE TITLE
Hello, does this script has "no Log VPN" feature? thank you

### ISSUE THREAD

**Issue by qnyblog** [zzzkeil/Wireguard-DNScrypt-VPN-Server#10]
Hello, does this script has "no Log VPN" feature? thank you

**Comment by zzzkeil** [comment]
?? maybe i don´t understand your question ??
If you are the server owner, you always has logs ..... 
If you want to share your server with others, with no logging at all, you have to adjust some settings, not only for wireguard, so for your os too.
But keep in mind, your responsible how other people use your server, beside from logging .......

**My main use case for this script:**
Smartphone always on VPN to tunnel all traffic, and block ads.
The VPN tunnel just helps to protect your traffic form the client to the server, in my case for eg. hotel or public hotspots.

At the end i´m using most of the time my server ip in the  word-wide-ads-and-usertracking world ... keep this in mind..

i have similar "test" script  that uses tor as "public ip"  its not up to date but worked : 
https://github.com/zzzkeil/wireguard-dnscrypt-tor-server

**Comment by qnyblog** [comment]
Thank you
