### ISSUE TITLE
nice to have for the client conf

### ISSUE THREAD

**Issue by Saugjunkie** [zzzkeil/Wireguard-DNScrypt-VPN-Server#11]
i think the conf can be bether when you integrated MTU and Keep alive.

what i think a good idea for endpoint is, when a option to use the hostname. then wireguard on pc can use ipv4 or ipv6 for endpoint. the programm change automatic the url in endpoint to a ip. 

one question about the range by ipv6 why you use not /64? i mean by ipv4 you use /24.

**Comment by zzzkeil** [comment]
Hi,
ok i have add this to my todo list 
- [ ] add option to change default MTU
- [ ] add option to activate keepalive and set value  

For ipv6 :   /112 and /64   maybe i change this in the versions. I have started the script with this and never changed it :)

**Comment by zzzkeil** [comment]
Your idea for using a hostname, is in my use case not the best option.
I prefer ipv4 to connect to my server, but i keep your wish in mind.

**Comment by zzzkeil** [comment]
for testing only  ( MTU and keepalive)  : 
https://raw.githubusercontent.com/zzzkeil/Wireguard-DNScrypt-VPN-Server/master/ubuntu/beta_test.sh

**Comment by zzzkeil** [comment]
> 
> 
> i think the conf can be bether when you integrated MTU and Keep alive.
> 
> what i think a good idea for endpoint is, when a option to use the hostname. then wireguard on pc can use ipv4 or ipv6 for endpoint. the programm change automatic the url in endpoint to a ip.
> 
> one question about the range by ipv6 why you use not /64? i mean by ipv4 you use /24.


for testing only  ( MTU and keepalive)  : 
https://raw.githubusercontent.com/zzzkeil/Wireguard-DNScrypt-VPN-Server/master/ubuntu/beta_test.sh

**Comment by zzzkeil** [comment]
done.
