### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by vendelieu** [zzzkeil/Wireguard-DNScrypt-VPN-Server#13]
After full installation
on last step get this trace ->

```
Scan the QR Code with your Wiregard App

 2 extra client configs with QR Codes created in folder : /etc/wireguard/

 add or remove clients with ./add_client.sh / remove_client.sh

 backup and restore options with ./wg_config_backup.sh / ./wg_config_restore.sh

Firewall is active and enabled on system startup
ERROR: problem running ufw-init
Bad argument `*filter'
Error occurred at line: 18
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Bad argument `*filter'
Error occurred at line: 19
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

Problem running '/etc/ufw/before.rules'
Problem running '/etc/ufw/before6.rules'
```

and after connecting to vpn can't visit to any site, like internet connection are lost

**Comment by vendelieu** [comment]
from install parameters didn't change anything except ssh port

**Comment by zzzkeil** [comment]
Server  or  Desktop  Ubuntu ?

**Comment by vendelieu** [comment]
server

**Comment by zzzkeil** [comment]
Ok,
plz, post your output from this command
lsb_release -a

my example Output :

comegetsome@vpn02server:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Comment by vendelieu** [comment]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Comment by vendelieu** [comment]
There's no tips?

**Comment by zzzkeil** [comment]
This weekend, i can look into this issue.

**Comment by vendelieu** [comment]
added
```
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```
to wg0 and it solved my problem

**Comment by zzzkeil** [comment]
Ok, but i don´t get this issue.
I try my script on a new clean Ubuntu 20.04 Server install > no issue.
the prebuild 20.04 image from my cloud provider works as well  without issue.
