### ISSUE TITLE
could you do something similar but with multiple servers ?  

### ISSUE THREAD

**Issue by notuos** [zzzkeil/Wireguard-DNScrypt-VPN-Server#14]
i mean client > vpn1 > vpn2 > vpn3 > internet ?

It would be just wonderful if there was such an opportunity.

**Comment by zzzkeil** [comment]
Hi, 
this is a little difficult to do for me now.
And a setup for this is not easy with just a script. 
**But.....
Maybe my other repository with routing traffic over tor, is something you can use instead.**

```
https://github.com/zzzkeil/wireguard-dnscrypt-tor-server 

** project target

    encrypted wireguard vpn connection to server
    all traffic from wireguard clients will go over tor network
    dns nameresulotion over dnscrypt (Anonymized DNS) with blocklists
    onion (darknet) nameresulotion over dnscrypt forward to tor

```
