### ISSUE TITLE
Reinstall or remove the script

### ISSUE THREAD

**Issue by zahareevici** [zzzkeil/Wireguard-DNScrypt-VPN-Server#2]
Hello, 
Update the readme and include how to reinstall or remove
Or how to generate config file for new client.

**Comment by zzzkeil** [comment]
Hi, 
i take look at it, but it takes a while.

**Comment by zzzkeil** [comment]
hi,
scripts and readme updated. 
I added a new file add_client.sh / remove_client.sh under 
[view the file under tools](https://github.com/zzzkeil/Wireguard-DNScrypt-VPN-Server/blob/master/tools/)
This file worked for me in my tests, but be careful on your system.

more coming soon.....
