### ISSUE TITLE
Great job !! 

### ISSUE THREAD

**Issue by aknik** [zzzkeil/Wireguard-DNScrypt-VPN-Server#3]
Have you think about Wireguard VPN + TOR ?
It will be great too XD
Thanks for you script !!

**Comment by zzzkeil** [comment]
Hi,
maybe sometime end of this year,

**Comment by aknik** [comment]
Thanks

**Comment by zzzkeil** [comment]
this project with tor   starts here :) 

Edit 
new name :
https://github.com/zzzkeil/wireguard-dnscrypt-tor-server

old name
https://github.com/zzzkeil/wireguard-tor-server
