### ISSUE TITLE
no internet connection after successful install

### ISSUE THREAD

**Issue by zahareevici** [zzzkeil/Wireguard-DNScrypt-VPN-Server#4]
After successful install of the script, server lost the internet connection, 
Any idea how to fix it?

**Comment by zzzkeil** [comment]
I installed the script on 2 fresh / clean Ubuntu 20.04 LTS Server without issues. -> hosted by Hetzner Germany

- Is the server lost the internet, or lost the clients internet connection ?
- Is your server running Ubuntu 20.04 ?
- Is your server running at home or in a datacenter (hoster) ?

**Comment by zahareevici** [comment]
Hello, 
I installed on local server with ubuntu 20.04
 I will try to reinstall the server today and I will check again, maybe I missed some steps.

**Comment by zahareevici** [comment]
update: 
I get this error in terminal:
```
root@remotehost:/etc/resolvconf# ping google.com
ping: google.com: Temporary failure in name resolution
```
strange thing is that I can send messages and make calls in whatsapp on client but I cannot open web pages

**Comment by zzzkeil** [comment]
ok lets try this first:
look in your dnscrypt logfile   -- > /var/log/dnscrypt-proxy.log
did you see any errors ? 

This is how the file normally looks like :  (example)

> [2021-01-02 21:06:15] [NOTICE] dnscrypt-proxy 2.0.44
> [2021-01-02 21:06:15] [NOTICE] Network connectivity detected
> [2021-01-02 21:06:15] [NOTICE] Now listening to 127.0.0.1:5353 [UDP]
> [2021-01-02 21:06:15] [NOTICE] Now listening to 127.0.0.1:5353 [TCP]
> [2021-01-02 21:06:15] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolvers over udp
> [2021-01-02 21:06:15] [NOTICE] Source [public-resolvers] loaded
> [2021-01-02 21:06:15] [NOTICE] Firefox workaround initialized
> [2021-01-02 21:06:15] [NOTICE] Loading the set of blocking rules from [blocklist.txt]
> [2021-01-02 21:06:16] [NOTICE] [doh.ffmuc.net] OK (DoH) - rtt: 23ms
> [2021-01-02 21:06:16] [NOTICE] [ffmuc.net-v6] OK (DNSCrypt) - rtt: 12ms
> [2021-01-02 21:06:16] [NOTICE] [dns.digitale-gesellschaft.ch-ipv6] OK (DoH) - rtt: 18ms
> [2021-01-02 21:06:16] [NOTICE] [dns.digitale-gesellschaft.ch] OK (DoH) - rtt: 19ms
> [2021-01-02 21:06:16] [NOTICE] Sorted latencies:
> [2021-01-02 21:06:16] [NOTICE] -    12ms ffmuc.net-v6
> [2021-01-02 21:06:16] [NOTICE] -    18ms dns.digitale-gesellschaft.ch-ipv6
> [2021-01-02 21:06:16] [NOTICE] -    19ms dns.digitale-gesellschaft.ch
> [2021-01-02 21:06:16] [NOTICE] -    23ms doh.ffmuc.net
> [2021-01-02 21:06:16] [NOTICE] Server with the lowest initial latency: ffmuc.net-v6 (rtt: 12ms)
> [2021-01-02 21:06:16] [NOTICE] dnscrypt-proxy is ready - live servers: 4

**Comment by zahareevici** [comment]
Here is the output:
root@remotehost:~$ cat /var/log/dnscrypt-proxy.log
[2021-01-03 21:26:33] [NOTICE] dnscrypt-proxy 2.0.44
[2021-01-03 21:26:33] [NOTICE] Network connectivity detected
[2021-01-03 21:26:33] [FATAL] listen udp 127.0.0.1:5353: bind: address already in use

**Comment by zzzkeil** [comment]
ok now, we know why your dns resolution is not working.

lets show which program is using port 5353

> netstat -tulpn | grep LISTEN

**Comment by zahareevici** [comment]
> root@remotehost:#  lsof -i -P -n
> COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> avahi-dae  3777   avahi   12u  IPv4  33690      0t0  UDP *:5353 
> avahi-dae  3777   avahi   13u  IPv6  33691      0t0  UDP *:5353 
> avahi-dae  3777   avahi   14u  IPv4  33692      0t0  UDP *:57845 
> avahi-dae  3777   avahi   15u  IPv6  33693      0t0  UDP *:37734

**Comment by zzzkeil** [comment]
ok try this in your case 

> systemctl stop avahi-daemon
systemctl disable avahi-daemon

restart the server

**Comment by zahareevici** [comment]
restarted, still persist:

> COMMAND     PID             USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> systemd-t  6380 systemd-timesync   14u  IPv4  50463      0t0  UDP 127.0.0.1:38187->127.0.0.53:53 
> avahi-dae  6395            avahi   12u  IPv4  40095      0t0  UDP *:5353 
> avahi-dae  6395            avahi   13u  IPv6  40096      0t0  UDP *:5353 
> avahi-dae  6395            avahi   14u  IPv4  40097      0t0  UDP *:56530 
> avahi-dae  6395            avahi   15u  IPv6  40098      0t0  UDP *:55498

**Comment by zzzkeil** [comment]
hmm....
is your avahi-deamon still running ?

check with systemctl status avahi-daemon
if yes you can uninstall  this one  -  apt remove avahi-daemon

**btw, is your server a standard Ubuntu 20.04 Desktop version ?**

**Comment by zahareevici** [comment]
fixed by removing, 
now cat /var/log/dnscrypt-proxy.log


> > [2021-01-03 22:05:25] [NOTICE] dnscrypt-proxy 2.0.44
> [2021-01-03 22:05:25] [NOTICE] Network connectivity detected
> [2021-01-03 22:05:26] [NOTICE] Now listening to 127.0.0.1:5353 [UDP]
> [2021-01-03 22:05:26] [NOTICE] Now listening to 127.0.0.1:5353 [TCP]
> [2021-01-03 22:05:36] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolvers over udp
> [2021-01-03 22:05:56] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolvers over udp
> [2021-01-03 22:06:06] [CRITICAL] Unable to retrieve source [public-resolvers]: [Get "https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md": dial tcp: lookup download.dnscrypt.info on 127.0.0.53:53: read udp 127.0.0.1:46837->127.0.0.53:53: i/o timeout]
> [2021-01-03 22:06:06] [FATAL] Get "https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md": dial tcp: lookup download.dnscrypt.info on 127.0.0.53:53: read udp 127.0.0.1:46837->127.0.0.53:53: i/o timeout

**Comment by zahareevici** [comment]
thank you for your help, I will try tomorrow to install o another server.

**Comment by zzzkeil** [comment]
is your server a standard Ubuntu 20.04 Desktop version ?  
Desktop Image : ubuntu-20.04.1-**desktop**-amd64.iso
or do you install your server with the server image ?
Server Image : ubuntu-20.04.1-**live-server**-amd64.iso
Download : https://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-live-server-amd64.iso

**Comment by zahareevici** [comment]
is a desktop version, tomorrow i will install server version

**Comment by zahareevici** [comment]
installed new Ubuntu 20.04 server edition (local), tested with android and wireguard app and I figure out that is working only when device is connected on the same wi-fi network, when I switch to mobile data than there is no internet connection.

**Comment by zzzkeil** [comment]
In this case, your wireguard app need your internet IP, and your router need the port open for your wireguard server.
If your wireguard app has the local IP, the app only can work in your local network.

**Comment by zahareevici** [comment]
thanks for you great job and support :+1:
