### ISSUE TITLE
-bash: ./add_client.sh: Permission denied

### ISSUE THREAD

**Issue by alexlii1971** [zzzkeil/Wireguard-DNScrypt-VPN-Server#5]
Hello,

After install on Ubuntu 20.04.2 LTS, it will show "command not found" when run both of the following command:

./add_client.sh 
./remove_client.sh

so what should I do please?

**Comment by zzzkeil** [comment]
https://github.com/zzzkeil/Wireguard-DNScrypt-VPN-Server/issues/8#issuecomment-808856497
