### ISSUE TITLE
what is Wireguard-DNScrypt-VPN-Server designed for please?

### ISSUE THREAD

**Issue by alexlii1971** [zzzkeil/Wireguard-DNScrypt-VPN-Server#6]
Hello,

I am fresh with Wireguard, would you please let me know what Wireguard-DNScrypt-VPN-Server is designed for? for local network? or for cloud VPS?

I installed it on Linode server, afterI found there are five clients after installation, and when I test on https://www.dnsleaktest.com/results.html

It will show as the screenshot:
http://prntscr.com/10de02g

On test at https://dnsleak.com/, it will show:
http://prntscr.com/10de8kx

Obviously, the server ip will show up on DNS leak test, is that expected please?

Thanks and have a nice day.

**Comment by zzzkeil** [comment]
In my case, its designed for cloud VPS 
The IP of your server will published to the world.
This script protect only the data form client to server.
For example, if you (the client) in a hotel network, or any unsecured, non trusted network.
If you wan´t to hide your IP to the world, i have this scrips in testing:

https://github.com/zzzkeil/wireguard-dnscrypt-tor-server
