### ISSUE TITLE
Hello, can you add Udp2raw-tunnel support or something similar? thank you

### ISSUE THREAD

**Issue by qnyblog** [zzzkeil/Wireguard-DNScrypt-VPN-Server#9]
Hello, can you add Udp2raw-tunnel support or something similar? thank you
ISP providers in some countries add QoS restriction, if use Udp2raw-tunnel can helps Bypass UDP masking or QoS restrictions

**Comment by zzzkeil** [comment]
hi,

to add this, i have to understand what Udp2raw-tunnel can do and what not, and how it can work with my script.
But this " Udp2raw-tunnel modification"  is needed on the server and on the client.....  
I think that is more like a modification **you should do**, after you installed my script.

I add this to my todo list, but its not prioritized.

Meanwhile take a look here : 
 - https://github.com/lrvl/tunnel-wireguard-udp2raw   (  based on wangyu ´s  udp2raw-tunnel )

**Comment by qnyblog** [comment]
thank you, have a nice day
